### ISSUE TITLE
No fuzzy matching?

### ISSUE THREAD

**Issue by p-schaefer** [gnames/gnverifier#105]
I'm not sure if GNV is meant to be a replacement for Global Names Resolver, but if it is, would it be possible to implement fuzzy matching? For instance, common typos such as Simulidae (incorrect) vs Simuliidae (correct) can't be correctly matched in ITIS with GNV but they could with GNR.

**Comment by dimus** [comment]
Thank you for feedback @p-schaefer. GNverifier does have fuzzy matching, however, for uninomials I did switch it off, as it was creating too many false positives. May be it would help to have an option to switch it on if needed?

And yes, GNResolver will be switched off eventually

**Comment by p-schaefer** [comment]
Thank you @dimus! Yes having the fuzzy matching as an option would be helpful in my work-flow.

**Comment by dimus** [comment]
@p-schaefer there is now an option in Web UI in the Advanced section for unionimials fuzzy matching. For commoand line tool the option would be `gnverifier -z Simulidae`
