### ISSUE TITLE
Post return incorrect name

### ISSUE THREAD

**Issue by rcDeveloping** [gnames/gnverifier#106]
When I try to run in R the following code

`library(httr)
library(jsonlite)

post_global_names <- httr::POST(
        "https://verifier.globalnames.org/api/v1/verifications",
        config = httr::add_headers(accept = "application/json",
                                   `Content-Type` = "application/json"),
        body = jsonlite::toJSON(list(nameStrings = c("Mezilaurus itauba"),
                                     dataSources = 197))
)

jsonlite::fromJSON(rawToChar(post_global_names$content))`

I get `Mezilaurus ita-uba` as anr answer in `bestResult.currentCanonicalSimple`  instead of `Mezilaurus itauba`

**Comment by dimus** [comment]
In this case you restrict your results to a data-source with id 197 `World Checklist of Vascular Plants`  (see https://powo.science.kew.org/results?q=Mezilaurus%20ita-uba).
According to them the matching canonical form would be **Mezilaurus ita-uba**, while running the query without data-source restriction would return best result as `Mezilaurus itauba` from Wikispecies:

https://verifier.globalnames.org/?capitalize=on&format=html&names=Mezilaurus+itauba
