### ISSUE TITLE
Orthographic variants of author names

### ISSUE THREAD

**Issue by larsgw** [gnames/gnverifier#107]
Searching for _Cimex biguttatus_ Linné, 1758 with `-s 11` returns the following results:

- _Cimex biguttatus_ Goeze, 1778
- _Cimex biguttatus_ Linnaeus, 1758
- _Cimex biguttatus_ Fabricius, 1775
- _Cimex biguttatus_ Schrank, 1801

I would like the second result to appear on top, if possible. I tried using advanced search, which returned no results even with `all:t`, so I would have to set fuzzy values for the name and the year myself, instead of matching them as needed. Is it possible to configure this somehow?

**Comment by dimus** [comment]
hm, gnverifier assumes that an author can be abbreviated in many different ways, but  fails if author is spelled differently. May be I should add a 'normalization' for such cases in the gnparser.
