### ISSUE TITLE
Updating datasets, iNaturalist and VASCAN in particular

### ISSUE THREAD

**Issue by frousseu** [gnames/gnverifier#108]
Hi

I started using this wonderful tool recently, but the outdated datasets make it difficult to get a match or translation for several species. For example, the last updates for VASCAN and iNaturalist are from 2012 and 2016 respectively. Are there any plans to update these datasets?

Thanks!
François

**Comment by dimus** [comment]
Thank you for your feedback @frousseu, iNaturalist and VASCAN are refreshed now, and I added them to the list of bi-annual updates.

https://verifier.globalnames.org/?all_matches=on&capitalize=on&ds=180&ds=147&format=html&names=Plantago+major

**Comment by frousseu** [comment]
Wow, thanks for the very fast update! For datasets with planned updates, it could be nice to have the planned update dates listed in the dataset pages or at least have the info about how frequently it is updated.
