### ISSUE TITLE
Incorrect (?) taxon parsing: Helicopsyche von Siebold 1856

### ISSUE THREAD

**Issue by BenMerSci** [gnames/gnverifier#118]
I am not sure if this is a gnverifier issue or ITIS (Integrated Taxonomic Information System) issue.

When the genus `Helicopsyche` is queried like [so](https://verifier.globalnames.org/api/v1/verifications/helicopsyche?capitalize=true&all_matches=true&data_sources=1|3|147) through gnverifier API, we get two results from Catalogue of Life and two results from ITIS.

I believe there is a parsing error in the second result from ITIS where in the classificationPath parameter, the last entry is `Helicopsyche von` but `von` is part of the authorship `von Siebold`.

I have not been able to verify if any other taxon identified with an authorship with a suffix (like `von Siebold`) have the same problem.

**Comment by dimus** [comment]
thanks for letting us know @BenMerSci, looks like it is classification import script for ITIS that creates the error. Parser does parse the genus correctly: https://parser.globalnames.org/?format=html&names=%09Helicopsyche+von+Siebold%2C+1856+&with_details=on

I am working on renewing data sources right now, so very timely observation, I will check if it is my ITIS import script to blame. Hopefully this error will disappear in a couple of weeks

**Comment by BenMerSci** [comment]
Thank you for the reply Dimus!
I'll check back in a couple of weeks

**Comment by dimus** [comment]
@BenMerSci, I updated ITIS and some other data-sources, and I do not see the error you spotted anymore. The harvesting is completely new now, and there is some chance I missed something, so if you see other problems, please let me know!

**Comment by BenMerSci** [comment]
I confirm that it is solved, thank you for the followup @dimus!
I will let you know if I find anything else.
