### ISSUE TITLE
VASCAN ClassificationIds suddenly missing

### ISSUE THREAD

**Issue by BenMerSci** [gnames/gnverifier#119]
The ClassificationIds key is not returned anymore for DataSource VASCAN (147) but is still returned by other sources like Catalogue of Life (1) and ITIS (3).

`Query example:`
https://verifier.globalnames.org/api/v1/verifications/salix?capitalize=true&all_matches=true&data_sources=1%7C3%7C147

**Comment by dimus** [comment]
thanks for letting me know @BenMerSci, I'll double check what could be a problem, hopefully will be fixed soon

**Comment by dimus** [comment]
VASCAN has both flat and tree hierarchies, and flat was default. Now, if tree hierarchy exists, it has a priority.

**Comment by dimus** [comment]
Hm, I just noticed that VASCAN is set as not curated, which actually means 'curation is unknown' I think it shoud be changed to 'curated'. It will be fixed next time database is updated

**Comment by BenMerSci** [comment]
Good to know!
Again, thank you so much @dimus !

**Comment by dimus** [comment]
you very welcome @BenMerSci, please do not hesitate to let me know if something else will appear, or if  there is a feature that is important but missing
