### ISSUE TITLE
taxonomicStatus defaults to "Synonym"

### ISSUE THREAD

**Issue by BenMerSci** [gnames/gnverifier#122]
The field `taxonomicStatus` seems to be defaulting to "Synonym" even when a valid scientific name is queried for example `Canis lupus` (status is valid for Catalogue of Life and ITIS)

`Query example`:
https://verifier.globalnames.org/api/v1/verifications/canis+lupus?capitalize=true&all_matches=true&data_sources=1%7C3%7C147

**Comment by dimus** [comment]
thanks for letting me know @BenMerSci, definitely a critical bug
