### ISSUE TITLE
502 bad gateway on 'phegopteris'

### ISSUE THREAD

**Issue by BenMerSci** [gnames/gnverifier#123]
I receive a code `502 bad gateway` when querying specifically for `phegopteris` for Catalogue of life, ITIS and VASCAN like so:

`https://verifier.globalnames.org/api/v1/verifications/phegopteris?capitalize=true&all_matches=true&data_sources=1%7C3%7C147`

I'm not  sure how to troubleshoot on my side as with other query with the same format with other taxons it works fine, for example:

`https://verifier.globalnames.org/api/v1/verifications/acer?capitalize=true&all_matches=true&data_sources=1%7C3%7C147`

Let me know if I can help in any way!

**Comment by dimus** [comment]
oups, for some reason I thought I did fix this one already! 

Now it should be fixed.
