### ISSUE TITLE
As a user I want a link to this issue tracker from the SWAGGER documention

### ISSUE THREAD

**Issue by mjy** [gnames/gnverifier#46]
When I come to the API, and i do some testing, or have a question, then I want a quick way to raise it here (if this is the canonical spot).

**Comment by dimus** [comment]
added to https://app.swaggerhub.com/apis-docs/dimus/gnames/1.0.0

    
    If you found a bug or want to request a feature for API, create an issue at
    https://github.com/gnames/gnames/issues
    
    If you use a web-site at https://verifier.globalnames.org or command line
    client from https://github.com/gnames/gnverifier and want to report a
    bug or request a feature, create an issue at 
    https://github.com/gnames/gnverifier/issues
