### ISSUE TITLE
Citation for Global Names Verifier

### ISSUE THREAD

**Issue by Rekyt** [gnames/gnverifier#52]
Hello @dimus 👋 
We've already interacted through the Global Names Gitter :)
I couldn't find a proper way to credit Global Names Verifier in an academic paper.
Is there a specific citation to use? If there is, then it could be nice to include it in the tool as well as on the corresponding website.

Many thanks again for building such a powerful tool!

**Comment by dimus** [comment]
Hi @Rekyt, this version of verifier is fresh out of oven, so there is no paper about it yet. Would it help if I make a DOI at Zenodo? I do plan a paper this or next year.

**Comment by Rekyt** [comment]
Thank you @dimus for your very quick answer :)
As a temporary solution having a DOI through Zenodo would be indeed helpful (if it's not too much work).
Because for the moment in paper that use Global Names Verifier we only use the name and the URL which may not be enough for most journals.
And I would ask you the same question for Global Names Index and Global Names Resolver.

**Comment by dimus** [comment]
Sounds good, @Rekyt, will be done next week, I am traveling for a few days, when I am settled, I'll make the DOIs

**Comment by dimus** [comment]
@Rekyt I am planning to retire GNindex and GNresolver when their functionality is moved to GNverifier. Can you tell what functionalities do you use in them?

**Comment by Rekyt** [comment]
@dimus thank you so much for the speed of your answer!

Regarding your question:

> @Rekyt I am planning to retire GNindex and GNresolver when their functionality is moved to GNverifier. Can you tell what functionalities do you use in them?

I'm actually using them to match species names on many databases at once (what they're supposed to do, right? ;)). But I'm right now in a the process of writing a manuscript on taxonomic harmonization and was considering recommending one of the three alternative in the main text while citing the two others as outdated or "soon to be outdated".
Should we indeed recommend only GNVerifier?

**Comment by dimus** [comment]
Yes it is better to recommend verifier only, and yes, I understood the purpose of citing older tools. I'll make doi for them as well, so when they are retired, there is still a good way to cite them.
