### ISSUE TITLE
Add classification path IDs to response

### ISSUE THREAD

**Issue by dshorthouse** [gnames/gnverifier#60]
The response structures in https://resolver.globalnames.org and here in gnverifier are somewhat different. The former additionally has `classification_path_ids`. Can this be added to the `gnverifier --format="pretty"` response?

**Comment by dimus** [comment]
As an example: https://verifier.globalnames.org/?all_matches=&all_sources=&capitalize=on&format=json&names=Bubo+bubo

Is `classificationIds` a correct subsitution for classification_path_ids?

**Comment by dshorthouse** [comment]
💯  Sure! Presence is more important than name of the key atm.
