### ISSUE TITLE
Adjust search to verify abbreviated names

### ISSUE THREAD

**Issue by dshorthouse** [gnames/gnverifier#61]
As mentioned here, https://github.com/AAFC-BICoE/dina-planning/issues/267 we have a use-case that hopes to search against sources using abbreviated genera in scientific names such as "D. limatus" and return candidate results.

**Comment by dimus** [comment]
In practice it means making the new faceted search functionality of `gnames` available via gnverifier client.

**Comment by dimus** [comment]
done in master branch. I will add it to web UI and release as 0.6.2_
