### ISSUE TITLE
questions about data sources available in globalnames/gnverifier searches

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnverifier#62]
I have just discovered gnverifier and I wonder if it does what I think it does. 
Sorry if some of these questions are perhaps more suitable for other gnames repositories:

- I understand gnverifier is just a way of accessing globalnames service without using a browser. But if I just want to use Python, is there any **difference** between using gnverifier (i.e. system calls from Python) or access [resolver.globalnames.org](https://resolver.globalnames.org) (api calls from Python)?
- Where can I read a bit about the reasons for some globalnames [Data Sources](http://resolver.globalnames.org/data_sources) being available and some others not? It's odd to me not seeing any of these global vascular plants databases: 
**WCVP** (_World Catalog of Vascular Plants_: see [website](http://wcvp.science.kew.org/), [dataset](http://sftp.kew.org/pub/data-repositories/WCVP/), [article](https://doi.org/10.1038/s41597-021-00997-6)), 
**LCVP** (_Leipzig Catalog of Vascular Plants_: see [dataset](https://github.com/idiv-biodiversity/LCVP) & [article](https://doi.org/10.1038/s41597-020-00702-z)), 
**WFO** (_World Flora Online_: see [website](http://www.worldfloraonline.org/), [dataset](http://www.worldfloraonline.org/downloadData) and [article](https://doi.org/10.1002/tax.12373))
All these offer whole dataset download links (instead of an API service). Is that the reason for them not being available?  
- Do globalnames and gnverifier search against the **original** data sources **web sites** (which could be offline sometimes) **or against globalnames-stored copies**? (AFAIK, many of the available datasets do not offer any API access point). 
So I hope it's just a matter of time seeing WCVP / LCVP / WFO copies available and searchable as well.
- In the mean time, does globalnames offer any other piece of software for **verifying names against a locally downloaded dataset** (i.e., download WCVP and run gnverifier -or whatever- against it, somehow)
- **Citation & versioning**: 
Shouldn't globalnames [Data Sources](http://resolver.globalnames.org/data_sources) page include **links to the original datasets**? It's hard for me to compare globalnames returned results against original datasource, if I can't access those data sources in some other way.
Also, I suppose some of the available data sources have versioning systems. How can we know **which version of the data source** is globalnames serving?

Please don't take these comments as criticism. I do like globalnames so much and I want to use and cite it. So I need to have a clear understanding of how it works.
Thanks a lot in advance for your answers.

**Comment by dimus** [comment]
>     * I understand gnverifier is just a way of accessing globalnames service without using a browser. But if I just want to use Python, is there any **difference** between using gnverifier (i.e. system calls from Python) or access [resolver.globalnames.org](https://resolver.globalnames.org) (api calls from Python)?

GNverifier is a faster version of resolve.globalnames.org and it has its own api: 

https://apidoc.globalnames.org/gnames

web interface is at https://verifier.globalnames.org, but the web UI is just 

`gnverifier -p 80` or something like that


So if you want to use python, it is better to use gnames service. API is not yet guaranteed to be backward compatible, but changes will not be very big.  resolver.globalnames.org is going to be retired somewhere in 2023 or the end of 2022.

>     * Where can I read a bit about the reasons for some globalnames [Data Sources](http://resolver.globalnames.org/data_sources) being available and some others not? It's odd to me not seeing any of these global vascular plants databases:

Some sources got into GNverifier by some weird chance and are not updated, but most important sources are updated 2 times a year (for resolver and verifier).

Some sources got by my own initiative, others were requested by users.

>       **WCVP** (_World Catalog of Vascular Plants_: see [website](http://wcvp.science.kew.org/), [dataset](http://sftp.kew.org/pub/data-repositories/WCVP/), [article](https://doi.org/10.1038/s41597-021-00997-6)),

I Think I can start harvesting it, nobody was asking for it before. Vascular plants ar mostly covered by Catalogue of Life (they use Michael Hassler World of Vascular Plants) and IPNI as a nomenclatural source.

>       **LCVP** (_Leipzig Catalog of Vascular Plants_: see [dataset](https://github.com/idiv-biodiversity/LCVP) & [article](https://doi.org/10.1038/s41597-020-00702-z)),

Another source that I can start harvesting.

>       **WFO** (_World Flora Online_: see [website](http://www.worldfloraonline.org/), [dataset](http://www.worldfloraonline.org/downloadData) and [article](https://doi.org/10.1002/tax.12373))

WFO is in plans for the year already. William Ulate is preparing their data for GNverifier, and estimation now is this December.

>       All these offer whole dataset download links (instead of an API service). Is that the reason for them not being available?

GNverivier uses whole datasets for everything, so it is not a problem.
> 
>     * Do globalnames and gnverifier search against the **original** data sources **web sites** (which could be offline sometimes) **or against globalnames-stored copies**? (AFAIK, many of the available datasets do not offer any API access point).

All data is downloaded and normalized with GNparser and other tools. So the service does not depend on
API of other resources.

>       So I hope it's just a matter of time seeing WCVP / LCVP / WFO copies available and searchable as well.
> 

I will investigate WCVP and LCVP availability. If all is good, they should appear in December/January in both resolver and GNverifier

>     * In the mean time, does globalnames offer any other piece of software for **verifying names against a locally downloaded dataset** (i.e., download WCVP and run gnverifier -or whatever- against it, somehow)
> 

Datasets must be normalized, and it is not a trivial task, so for  now it is not possible yet. If I will greate a registry for automatic download of data say, in DarwinCore format, such thing wil be possible. 

>     * **Citation & versioning**:
>       Shouldn't globalnames [Data Sources](http://resolver.globalnames.org/data_sources) page include **links to the original datasets**? It's hard for me to compare globalnames returned results against original datasource, if I can't access those data sources in some other way.

You can find links for databases (if i know them) on this page:

https://verifier.globalnames.org/data_sources
Also, when possible GNverifier provides links back to the original data.

However,  I do think citation shoud be improved.

>       Also, I suppose some of the available data sources have versioning systems. How can we know **which version of the data source** is globalnames serving?

I did not figure out how to normalize versioning from the sources yet. I would say it can be done manually, but I did not get to that yet. You can sort of estimate how fresh data is by the date of upload:
https://verifier.globalnames.org/?all_matches=&all_sources=&capitalize=on&format=html&names=Plantago+major

> Please don't take these comments as criticism. I do like globalnames so much and I want to use and cite it. So I need to have a clear understanding of how it works. Thanks a lot in advance for your answers.

Constructive feedback like yours is very welcomed! Thank you @abubelinha

**Comment by abubelinha** [comment]
Thanks a lot to you @dimus. I am indeed very interested in those vascular plants datasets being available.
> https://verifier.globalnames.org/data_sources
> Also, when possible GNverifier provides links back to the original data.

Thanks for that link (it shows much more info about data sources than [http://resolver.globalnames.org/data_sources](http://resolver.globalnames.org/data_sources)).
I am curious about [the last data source (195)](https://verifier.globalnames.org/data_sources/195), updated last month. Where did you download the dataset from? I see their website is searchable but I can't find any links to the dataset.
> Datasets must be normalized, and it is not a trivial task, so for now it is not possible yet. If I will greate a registry for automatic download of data say, in DarwinCore format, such thing wil be possible.

Even if it's far beyond my understanding, I wonder if that normalization process it is somehow documented. I am curious about it.

Also, [I asked this question](https://github.com/gnames/gnmatcher/issues/39) about a much simpler task but I wonder if you have any advices on how to accomplish it from Python. Would you use any gnames app or not? (I posted it under gnmatcher because I didn't know which gnames project could be closer to my question).

**Comment by dimus** [comment]
> I am curious about the last data source (195), updated last month. Where did you download the dataset from? I see their website is searchable but I can't find any links to the dataset.

Algaebase usually is not shared with other projects, I just got lucky, and they agreed to share their names.

> Even if it's far beyond my understanding, I wonder if that normalization process it is somehow documented. I am curious about it.

I use https://github.com/GlobalNamesArchitecture/dwca_hunter for this purpose. When I get resources, I will make a faster harvester, and, hopefully a registry so people can provide data sources themselves.

> Also, I asked this question about a much simpler task 

I'll answer your question at gnmatcher

**Comment by abubelinha** [comment]
Regarding the possibility of having a registry to let people provide data sources, I think that's a great idea.

This make me ask if, as a data provider, I could also run a gnames web service providing name matching services but **limited only to those datasets of my interest** (i.e., my own data and perhaps also a small subset of certain plants and fungi datasets, but filtering only the names of those taxa occurring in my region). Is this in theory possible? And specially, would this permite to reduce the [hardware requeriments](https://github.com/gnames/gnames#installation-prerequesites)? 

In [gnames documentation](https://github.com/gnames/gnames#installation-process) I see it's possible to download a gnames pgsql database dump, so after doing it, I could filter out the vast majority of data and finally try to insert my own information.
LOL ... assuming I am able to understand the database. Is there a gnames ER schema available somewhere?

By the way, many of the [data sources](https://verifier.globalnames.org/data_sources) versions are quite recent: 1, 2, 3, 5, 9, 11, 12 ... (many more) ... 193, 194, 195: were updated during 2021. 
But the linked database dump is quite old ([gnames-latest.sql.gz 28-Nov-2020](http://opendata.globalnames.org/dumps/gnames-latest.sql.gz)). 
I also see a very recent [all-names-2021-11-14.txt](http://opendata.globalnames.org/dumps/all-names-2021-11-14.txt) file.
Perhaps the dump format has changed somehow and the documentation has to be updated?
Or perhaps the txt file is a completely different auto-generated thing, not suitable to regenerate the database?

Thanks a lot!

**Comment by abubelinha** [comment]
Regarding the verifer api you mentioned above, 

> GNverifier is a faster version of resolver.globalnames.org and it has its own api:
> https://apidoc.globalnames.org/gnames

I see a major difference with https://resolver.globalnames.org/api
In resolver, I could send an id for each of the names in my list:
```
my-id-1|Parus major
my-id-2|Corvus corax
my-id-2|Ciconia ciconia
...
```
I suppose those ids were necessary because there is no guarantee that the results array will be sorted in the same order as the requested names. Correct?

But in https://apidoc.globalnames.org/gnames I don't see an option for setting this identifiers.
Does this mean the order in the API response is guaranteed now to match the order of requested names?

Thanks

**Comment by dimus** [comment]
@abubelinha I am trying a simpler approach to off-line names matching. Take a look at https://github.com/gnames/gndiff. It is a project that allows to compare two sci. names datasets against each other. Let me know if it covers all/some of your needs. If you do have a feedback, please open tickets at `gndiff` repo

**Comment by dimus** [comment]
WFO is added with id 196, WCVP and LCVP are in https://github.com/GlobalNamesArchitecture/dwca_hunter/issues/55
and https://github.com/GlobalNamesArchitecture/dwca_hunter/issues/54

**Comment by abubelinha** [comment]
Sorry, I was busy with other projects last month and had missed your last comments. 

Regarding the new data sources:
- Not important, but WFO ([196](https://verifier.globalnames.org/data_sources/196)) looks like to have some odd description format? 
- WCVP & LCVP. Could you explain their status? I already see their entries in verifier ([197 WCVP](https://verifier.globalnames.org/data_sources/197) &  [198 LCVP](https://verifier.globalnames.org/data_sources/198)). But you commented they are in dwca_hunter (don't know what that means, specially for LCVP where you [mentioned inconsistencies](https://github.com/GlobalNamesArchitecture/dwca_hunter/issues/55#issuecomment-1003121704)).

Versions available in verifier are already expected to work correctly? (I guess the names with inconsistencies would have been filtered out?)

Regarding [gndiff](https://github.com/gnames/gndiff), it sounds really great ... but I still have to check it (have seen your posts right now).
Thanks for all this!  A lot!!

**Comment by dimus** [comment]
> Not important, but WFO ([196](https://verifier.globalnames.org/data_sources/196)) looks like to have some odd description format?

yeah, hopefully they will fix it in their DwCA file next time.

> WCVP & LCVP. Could you explain their status? I already see their entries in verifier ([197 WCVP](https://verifier.globalnames.org/data_sources/197) & [198 LCVP](https://verifier.globalnames.org/data_sources/198)). But you commented they are in dwca_hunter (don't know what that means, specially for LCVP where you https://github.com/GlobalNamesArchitecture/dwca_hunter/issues/55#issuecomment-1003121704).

I use legacy harvester for resolver.globalnames.org, until I make a new harvester for gnverifier. As a result changes in resolver always get to gnverifier, so the databases are mostly in sync. 

https://github.com/GlobalNamesArchitecture/dwca_hunter is a legacy tool  I made to create Darwin Core files out of all kind of
formats different datasets come up with. When I move data from whatever format to DwCA all the inconsistencies in a dataset appear. I found quite a few in LCVP and even made an Issue for them.

**Comment by dimus** [comment]
There are two statuses for datasets - included into resolver/gnverifier and not included ;)

**Comment by abubelinha** [comment]
Hi @dimus 

This recent publication is quite related to several datasets of vascular plants available in Global Names ([196](https://verifier.globalnames.org/data_sources/196), [197](https://verifier.globalnames.org/data_sources/197), [198](https://verifier.globalnames.org/data_sources/198) plus [WorldPlants](https://www.worldplants.de), which you might like to include too). 
It compares their contents and also addresses problems parsing the names and so on:

_The big four of plant taxonomy – a comparison of global checklists of vascular plant names_
https://doi.org/10.1111/nph.18961

I bet you already know it, but just in case

**Comment by dimus** [comment]
Hi @abubelinha, I am planning biannual update in February/March and will definitely update 195 as well. Let me know if it is important for you to  have it earlier, I can do it one of the first data-sources, sadly January is quite taken for other things for me.

**Comment by abubelinha** [comment]
Thanks @dimus 
Yes, 195 is definitely the most important update compared to any other data-sources. It is by far the most complete nomenclatural database for that taxonomic group. And it is not shared with any other projects but Global Names. So yes: it is crucial to update it as frequently as possible.
