### ISSUE TITLE
question about cf. in input

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnverifier#64]
Some results of my Pythn calls to https://verifier.globalnames.org/api/v1/verifications/

- Input 1: Phacopsis oxyspora var. defecta Triebel & Rambold
Bestresult: [Index Fungorum (5) 413758]: Phacopsis oxyspora var. defecta Triebel & Rambold 1995

- Input 2: Phacopsis oxyspora **_cf._** var. defecta Triebel & Rambold
Bestresult: [Catalogue of Life (1) 4FKN3]: Phacopsis oxyspora (Tul.) Triebel & Rambold
Preferred: [Index Fungorum (5)134632]: Phacopsis oxyspora (Tul.) Triebel & Rambold [1988](https://github.com/gnames/gnverifier/issues/65)

I would expect that with or without "cf.", the input should match the infraspecific rank.
But when "cf." is present gnames matched the next higher taxonomic rank (not sure if this is on purpose or not)

I have only seen this with infraspecific ranks input. With species input, that is not happening:

- Input 3: Phacopsis **_cf._** oxyspora
Bestresult: [Catalogue of Life (1) 4FKN3]: Phacopsis oxyspora (Tul.) Triebel & Rambold
Preferred: [Index Fungorum (5)134632]: Phacopsis oxyspora (Tul.) Triebel & Rambold [1988](https://github.com/gnames/gnverifier/issues/65)

May this be a bug, or should I take care of removing "cf." myself from input, to get my expected results in output?
I linked years above to a different question. Thanks!

**Comment by dimus** [comment]
The reason behind it is the semantic meaning of 'cf.' in the name https://en.wikipedia.org/wiki/Cf.

GNparser considers names with `cf.` to be be `surrogates`, assuming someone could not identify species correctly, and compared them to something that they are 'not'. So in this case it would be a mistake to match such name with details after `cf.` annotation.

**Comment by abubelinha** [comment]
Yes, I understand what you mean. 
The [part of the name after _cf._ is just a guess/suggestion](https://en.wikipedia.org/wiki/Cf.#Biological_use) (might or might be not be correct). So gnverifier takes the more conservative approach and decides not to take it into account: 
> So in this case it would be a mistake to match such name with details after cf. annotation.

No problems with that (if I do prefer to be risky, I could just remove _" cf. "_ from the names in advance)

But the same gnverifier logic should be applied to both specific and infraspecific ranks. Shouldn't it?

You say _Phacopsis **cf.** oxyspora_ should be matched to _Phacopsis_ (and not _Phacopsis oxyspora_), 
But [that's not happening](https://verifier.globalnames.org/api/v1/verifications/Phacopsis%20cf.%20oxyspora).
Am I missing something?

**Comment by dimus** [comment]
> You say Phacopsis cf. oxyspora should be matched to Phacopsis (and not Phacopsis oxyspora),

looks like a bug in gnparser, adding an issue there

**Comment by dimus** [comment]
https://github.com/gnames/gnparser/issues/216

**Comment by dimus** [comment]
I was wrong actually @abubelinha, gnparser suppose to stop parsing if 'aff.' used, while for 'cf.' we decided to parse name anyway,
but issue a warning and bring quality to 4. So you are correct that `Phacopsis oxyspora cf. var. defecta Triebel & Rambold` should give the same canonical as `Phacopsis oxyspora var. defecta Triebel & Rambold` according to our rules. I just did not implement 'cf.' for infraspecies yet. So I will change gnames/gnparser#216 accordingly

**Comment by abubelinha** [comment]
Thanks @dimus  
I agree: [_**aff.** xxx_](https://en.wikipedia.org/wiki/Species_affinis) means "this resembles but **is different** to _xxx_" (a negative meaning).
But [_**cf.** xxx_](https://en.wikipedia.org/wiki/Cf.#Biological_use) means "this **could be** _xxx_" (a positive meaning, saying nothing against _xxx_).
