### ISSUE TITLE
parameter for avoiding publication year in plant names output

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnverifier#65]
- Input 3: Phacopsis [cf.](https://github.com/gnames/gnverifier/issues/64) oxyspora
Bestresult: [Catalogue of Life (1) 4FKN3]: Phacopsis oxyspora (Tul.) Triebel & Rambold
Preferred:  [Index Fungorum (5)134632]: Phacopsis oxyspora (Tul.) Triebel & Rambold **1988**

See the difference between names returned by Catalogue of Life (without publication year) and Index Fungorum (with year).

As I do prefer to use Index Fungorum, would it be possible to have a parameter to always remove years from matchedName or currentName outputs? (no matter which data source they come from)  
That might be easy if names stored in database are already parsed (otherwise I suppose some regex to output would be a better choice)

**Comment by dimus** [comment]
I would not llike to be in a business of "improving" a data-source vision. In this case Paul Kirk decided that he prefers to provide a year meta-information in Index Fungorum and was kind to take his time and create a data dump for GN. I think I should show his names according to his vision. However I DO "improve" names if there is a choice between not finding them at all, or introducing a minor change to make them compatible with other records in a database ( for example https://verifier.globalnames.org/?all_matches=&all_sources=&capitalize=on&format=html&names=Cyclidiopsis+korsikovii)

And, as you mentioned, the end-user can use gnparser to modify names according to their needs

**Comment by abubelinha** [comment]
Yes, no problem at all. 
I was asking a general option for removing years, similar to other user options such as `capitalize=on` as in the link you provided (I guess you meant `capitalize` with that link?)

**Comment by dimus** [comment]
`capitalize` option is for input, not output, it is for 'lazy' people who want to write `potentila` instead of `Potentila` in their search
