### ISSUE TITLE
Author L without terminal period makes unparsed tail

### ISSUE THREAD

**Issue by dshorthouse** [gnames/gnverifier#75]
When the author "L" without terminal period is used in a query, the result makes for an unparsed tail.

Example: https://verifier.globalnames.org/api/v0/search/n:P.+moesta+L+ds:1

Compared to: https://verifier.globalnames.org/api/v0/search/n:P.+moesta+L.+ds:1

**Comment by dimus** [comment]
hm, I wonder if it there is any use of an exact match of a one-letter author. May be the right thing to do here is to parse it, but do not try to search for 'L' author and give a warning
`one-character author "L" is ignored, may be you forgot a period at the end?`

**Comment by dshorthouse** [comment]
That's a possible solution although `L` (without a period) is likely to be very common.

**Comment by dimus** [comment]
Yes, I think it is better to let L to be searched as is. It will be less surprizing for a user.

**Comment by dimus** [comment]
Should work now (gnverifier v0.6.6, gnames v0.5.12)
