### ISSUE TITLE
Virus names?

### ISSUE THREAD

**Issue by dshorthouse** [gnames/gnverifier#76]
Are virus names out-of-scope for gnverifier? They appear to be handled on https://resolver.globalnames.org/ but attempts to find eg `Tobacco mosaic virus` (as present in the Catalogue of Life) return no match.

**Comment by dshorthouse** [comment]
Thanks, @dimus!

**Comment by dimus** [comment]
Accidently I found an awesome Go standard library for this task
https://eli.thegreenplace.net/2016/suffix-arrays-in-the-go-standard-library/

**Comment by cgendreau** [comment]
Thanks @dimus !

It seems to work on https://verifier.globalnames.org/api/v0/verifications/Tobacco%20rattle%20virus

Should we point to v0 instead of v1 ?

**Comment by cgendreau** [comment]
yes, I'm planning to use `/search` but since viruses were not working I wasn't sure.

**Comment by dshorthouse** [comment]
Perhaps one way to handle this, though might be cumbersome to implement & will incur an additional delay in the front-end, is for the client to take a first pass at `/verifications` but then fall-back to `/search` when `names[0][matchType] == "NoMatch"` in the first response.

**Comment by dimus** [comment]
Viruses are different from other names, they do not have a parsing stage and are simply matching as a substring from the start of virus names in database. For example 

https://verifier.globalnames.org/api/v0/verifications/Influenza%20B%20virus?data_sources=4&all_matches=true

Shows that strings matching `Influenza B virus` might have additional strain info, or an annotation and still match.

Search relies on knowing where a name-string has genus, species authors, years etc. For viruses such information is much harder to get at the moment, so they are not parsed and cannot be found by `search`

@cgendreau `api/v1` does not support any new stuff, so `api/v0` is the right choice.

Output-wise verification and search return the same structure, so you can rely on consistency in result fields. The only difference is that in JSON output some empty fields are not returned to save bandwidth.

Here is the definition of a Name output 

https://github.com/gnames/gnlib/blob/master/ent/verifier/name.go

**Comment by dimus** [comment]
the idea for `api/v0` is to add new things (like search), and, if needed, make changes in fields names etc. I suspect that the main changes are done already, and now it will mostly be appended with additional fields (like vernaculars).

When it stabilizes, it will become `/api/v2` 

`/api/v1` exists for people who already made scripts for it, or who did not upgrade their gnverifier

**Comment by dimus** [comment]
I would use API like this:

0. Try to parse a name with gnparser to see if it is a virus or not.

1. If I have a whole name and I believe it is "correct", if I go throuh many names: `api/v0/verification`
2. If a name is tricky, and I go one name at a time: `/api/v0/search`
3. If a virus use `api/v0/verification`

I would not use `api/v1`

**Comment by dshorthouse** [comment]
Thanks, @dimus. This is partly a client implementation issue. Your 

> 0. Try to parse a name with gnparser to see if it is a "virus" or not.

May not be possible in all instances, especially if the client's integration (as is ours) operates almost entirely in the front-end with user-supplied content. Now, if there was a NodeJS-based port of gnparser, that *could* be a solution to help shunt the calls to one API vs the other.

**Comment by dshorthouse** [comment]
Aha! @cgendreau See https://github.com/amazingplants/node-gnparser

**Comment by dimus** [comment]
@cgendreau, @dshorthouse, please look at https://github.com/gnames/gnames/releases/tag/v0.8.0

I am going to publish it today. This release contains several incompatible changes (mostly for verification) 
Docs are updated https://apidoc.globalnames.org/gnames-beta

**Comment by cgendreau** [comment]
thanks @dimus . How can I test it from the api? Is it already running behind api/v0 ?

**Comment by dimus** [comment]
@cgendreau yes, it is live 

https://verifier.globalnames.org/api/v0/verifications/Pomatomus%20soltator%7CBubo%20bubo%7CIsoetes%20longissimum

returns `bestResult` for each name, field `results` is empty

https://verifier.globalnames.org/api/v0/verifications/Pomatomus%20soltator|Bubo%20bubo|Isoetes%20longissimum?data_sources=11|12

Only queries results from data-sources 11 and 12

https://verifier.globalnames.org/api/v0/verifications/Pomatomus%20soltator|Bubo%20bubo|Isoetes%20longissimum?all_matches=true

provides all found matches in `results`, field `bestResult` is null

https://verifier.globalnames.org/api/v0/verifications/Pomatomus%20soltator|Bubo%20bubo|Isoetes%20longissimum?all_matches=true&data_sources=11,12

returns all matches found in 11 and 12 data-sources
