### ISSUE TITLE
correct urls for api requests + problem in local api url

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnverifier#78]
Sorry @dimus but I am a bit lost regarding which should be the preferred url to use when launching api requests to gnverifier. 

This is what my python script was using:

url = "https://verifier.globalnames.org/api/v1/verifications/"

But today I noticed that for some parameters (i.e. `preferred_only=on`), the response ignores them (I am getting `bestResult` returned anyway).

Maybe related to api changes mentioned in #68 ? 
What api url should I use to receive the same json responses as if were using the web interface?  https://verifier.globalnames.org/ (where `preferred_only` switch works OK)

Also, from #68 I understood some features like `scoreDetails` were new implementations. But I am confused about that: I see them when calling v0, but not in v1.

I suppose the answers to these questions would apply also to urls used when running gnverifier.exe as a local server.  But in that case, I am having an additional issue.

`gnverifier -p 8052`

While the server is running correctly at the specified port (i.e., I have the same interface as in https://verifier.globalnames.org/ ), the verifier API is not working.

All these return expected results, except the last one:
1. http://verifier.globalnames.org/?&format=json&names=Tradescantia+fluminensis
2. http://192.168.1.8:8052/?&format=json&names=Tradescantia+fluminensis
3. http://verifier.globalnames.org/api/v1/verifications/Tradescantia%20fluminensis
4. http://192.168.1.8:8052/api/v1/verifications/Tradescantia%20fluminensis

Output is identical in 1 & 2, but not in 3 & 4. The last one returns:
`{"message":"Not Found"}`

I tried with both v0.5.2 and v0.6.6 (Windows 10). 
I am launching them the same way I had already used for a gnparser local API server (that works great, as I had mentioned [here](https://github.com/gnames/gnparser/issues/192#issuecomment-962194689))

Thanks a lot in advance

**Comment by dimus** [comment]
@abubelinha, if you want "stable until dead" API, it is better to use `/api/v1`

if you want to have "currently developed with new features, but less stable" then use `/api/v0`.

https://apidoc.globalnames.org/ has both of them documented. I think /api/v0 is stabilizing now, so I do not expect huge changes there. When I feel it is doing all what it should do, I will release v1.0 for  gnverifier, gnames, gnmatcher, and the api/v0 will become /api/v2

**Comment by dimus** [comment]
https://verifier.golobalnames.org got updated to v0.7.0, and I am going to actively develop all 3 verificatons for the next few days, so website might be a bit ahead of binaries for the next couple of days

**Comment by dimus** [comment]
When you call GET method on local recent gnverifier, it still goes to the remote /api/v0

It is just a convenience feature, so if someone has a question about a name, or want to submit a bug about a name verification, they can illustrate their question/problem with a URL  like one you provided:

http://verifier.globalnames.org/?&format=json&names=Tradescantia+fluminensis

**Comment by abubelinha** [comment]
OK ... thanks a lot for clarifying multiple api versions.

I was assuming that gnverifier -p option was very much like gnparser (I thought the request would be redirected to a remote verifier api, so I could serve a "local api" for other machines which are restricted to LAN). 
Understood now. It's not really that important.
 
Regarding my `preferred_only=on` failures, I still have not clear if this should work or not in any of the api versions. Any api url example? (where I set preferred `data_sources` and `bestResult` is _**not**_ returned)

I also take the opportunity to ask ... where can I see an explanation of the different current/matched canonical names returned? Or an api url example where they show different values (i.e. `matchedCanonicalSimple` vs `matchedCanonicalFull`).
I think I had read about that somewhere before, but I don't recall where it was.

Thanks a lot for your patience

**Comment by dimus** [comment]
hm, `preferred_only` is actually currently a presentation modification feature of `gnverifier`. I guess I can add it to API

there is a [secton](http://localhost:6419/#getting-the-simplest-possible-canonical-form) about it in the gnparser docs. I added a table there, so it is a bit easier to find.

**Comment by abubelinha** [comment]
Thanks a lot again.
I just was wondering why `preferred_only` didn't work in API. Your clarification is enough. 
Don't worry, I will just skip `bestResult` when I don't need it. 

I think you posted a bad link?

**Comment by dimus** [comment]
oupsI meant https://github.com/gnames/gnparser#getting-the-simplest-possible-canonical-for
