### ISSUE TITLE
EUNIS datasource outdated (updated exactly 10 years ago)

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnverifier#81]
Regarding the example in #80, the mentioned [EUNIS datasource](http://verifier.globalnames.org/data_sources/158) results are very outdated.

In the example provided, [verifier shows](http://verifier.globalnames.org/?all_sources=on&format=json&names=Isoetes%20longissimum%20Bory&all_matches=true) both "currentRecordid" & "recordId="144750512", which does not match the taxon id 316085 shown in the [EUNIS url ... where _Isoetes longissimum_ is reported as a synonym of _I. longissima_](https://eunis.eea.europa.eu/species/316085)

Is it possible to update that datasource?  I think there is a pretty recent version in [COL CheckListBank](https://data.catalogueoflife.org/dataset/2122/) (already contains the [above example reported as a synonym](https://data.catalogueoflife.org/dataset/2122/taxon/194389), and shows the same id as EUNIS).

This datasource is pretty [interesting for European regional checklists](https://eunis.eea.europa.eu/about).

Thanks a lot in advance !!

**Comment by dimus** [comment]
Looks like they do have a dump, at leas in RDF from 2020, so I can use it to update EUNIS. I do have to deal with other things for a few months though. Usually I reserve time in December/January, May/June for data updates

**Comment by dimus** [comment]
Do they have DwCA file at GBIF? if yes, I can stick it in fast

**Comment by abubelinha** [comment]
Actually they do, but it might be the same old version:
https://www.gbif.org/dataset/1bd42c2b-b58a-4a01-816b-bec8c8977927
Publication date January 1, 2010

Perhaps you get it from there too, 2 years later?
It doesn't seem to have synonyms links between taxon ids.
https://www.gbif.org/species/101280862/verbatim

I actually discovered it here at gnames, and then searched for it at COL to pass you the links.
Why don't you use the download options at COL? (I think one of them is DwCA)

**Comment by dimus** [comment]
ah ok, yes, with all probability it is the same file that I used. OK, i'll add EUNIS it to the queue for May

**Comment by abubelinha** [comment]
> ah ok, yes, with all probability it is the same file that I used. OK, i'll add EUNIS it to the queue for May

Just wondering ... was this just forgotten, or is there any problem with the DwCA file?
Thanks

**Comment by dimus** [comment]
Thanks for reminding about this one @abubelinha, I did forget about it. I will get back to it sometime in the second half of September.

**Comment by dimus** [comment]
EUNIS is updated now
