### ISSUE TITLE
preferred results are missing in API v0 json return

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnverifier#82]
Playing with the examples in #80 I guess I have found a new, different issue: 

Preferred results are not even being returned in API v0.
Neither as preferredResults (old name) nor as results. 

I post the same example and preferred source taken from #68 , which I think was a question about different names -`results`/`preferredResults`- for the same concept, in output returned by gnverifier executable.

This time I tried the same request, but using the API:
- [v1](http://verifier.globalnames.org/api/v1/verifications/Quassia%20amara?pref_sources=179&all_matches=true): `preferredResults` array is there
- [v0](http://verifier.globalnames.org/api/v0/verifications/Quassia%20amara?pref_sources=179&all_matches=true): `results` array is not there

Is this intended behaviour?  Looks like an API bug to me.

**Comment by dimus** [comment]
Probably this query?

https://verifier.globalnames.org/api/v0/verifications/Pomatomus%20soltator%7CBubo%20bubo?data_sources=0

**Comment by dimus** [comment]
@abubelinha I will add a link to v1 to v0 apidoc, and a link to v0 at v1 doc in a meanwhile all docs are listed at
 
https://apidoc.globalnames.org

**Comment by abubelinha** [comment]
Thanks a lot, those links are really handy!

**Comment by dimus** [comment]
links are in place for gnames v0 and v1 docs

**Comment by abubelinha** [comment]
OK but ... when you say "are in place" you mean in a new place?
... or in the page you linked above https://apidoc.globalnames.org/ ?

**Comment by dimus** [comment]
I added crosslinks to each other at  https://apidoc.globalnames.org/gnames-beta and https://apidoc.globalnames.org/gnames
