### ISSUE TITLE
PartialExact match instead of Fuzzy  ??

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnverifier#83]
I am going back from verifier to resolver's api for a while, because for my use case it is crucial that all found fuzzy matches are returned.

I have just discovered a new verifier odd match (IMHO). 
- preferred sources: 196,197,198
- datasource name: Isoetes longi**ss**ima (in all 3 sources)
- input name: Isoetes longi**s**ima (bad-spelled: "s" instead of "ss")
- [resolver's output](http://resolver.globalnames.org/name_resolvers.json?names=Isoetes%20longisima&data_source_ids=196|197|198): 3 expected matches ("Fuzzy match by canonical form"): _Isoetes longissima_ in all data sources
- [verifier's output](http://verifier.globalnames.org/api/v1/verifications/Isoetes%20longisima?pref_sources=197|196|198&all_matches=true): 6 unexpected matches (all "PartialExact"), all really odd to me (either genus rank, or an unrelated hybrid name ... but none of them matches with _Isoetes longissima_). Not even the bestResult is useful (PartialExact match against genus _Isoetes_)

Looking to the list of [sequential matches explained in resolver's api](http://resolver.globalnames.org/api), it looks like to me that verifier is giving step 6 a higher priority than steps 3-5?:

> **match_type**
> Explains how resolver found the name. If the resolver cannot find names corresponding to the entire queried name string, it sequentially removes terminal portions of the name string until a match is found.
> 1 - Exact match
> 2 - Exact match by canonical form of a name
> 3 - Fuzzy match by canonical form
> 4 - Partial exact match by species part of canonical form
> 5 - Partial fuzzy match by species part of canonical form
> 6 - Exact match by genus part of a canonical form
>

**Comment by dimus** [comment]
@abubelinha can you provide an example where resolver API does the right thing for you?

**Comment by dimus** [comment]
@abubelinha, thank you very much for reporting this bug. It was an obscure typo in sql query, that prevented quite a few names with different suffixes get their fuzzy matching. Should work now:

https://verifier.globalnames.org/?all_matches=&all_sources=&capitalize=on&format=html&names=Isoetes+longisima
